data = {'60017^MNDRY_LOC_CONSCIOUS^99MNDRY': {'Conscious': '意识等级', 'The patient is conscious.': '说明'},
        '60018^MNDRY_LOC_CONFUSED^99MNDRY': {'Confused': '意识等级', 'The patient is confused.': '说明'},
        '60019^MNDRY_LOC_DELIRIOUS^99MNDRY': {'Delirious': '意识等级', 'The patient is delirious.': '说明'},
        '60020^MNDRY_LOC_SOMNOLENT^99MNDRY': {'Somnolent': '意识等级', 'The patient is somnolent.': '说明'},
        '60021^MNDRY_LOC_OBTUNDED^99MNDRY': {'Obtunded': '意识等级', 'The patient is obtunded.': '说明'},
        '60022^MNDRY_LOC_STUPOROUS^99MNDRY': {'Stuporous': '意识等级', 'The patient is stuporous.': '说明'},
        '60023^MNDRY_LOC_COMATOSE^99MNDRY': {'Comatose': '意识等级', 'The patient is comatose.': '说明'},
        '60044^MNDRY_LOC_UNKNOWN^99MNDRY': {'Unknown': '意识等级', 'The patient’s level of conscious is not known.': '说明'},
        '60000^MNDRY_POS_STANDING^99MNDRY': {'Standing': '体位', 'The patient is in a standing position': '说明'},
        '60001^MNDRY_POS_SITTING^99MNDRY': {'Sitting': '体位', 'The patient is in a sitting position': '说明'},
        '60002^MNDRY_POS_SUPINE^99MNDRY': {'Supine': '体位', 'The patient is laying on their back': '说明'},
        '60003^MNDRY_O2_SRC_ROOM^99MNDRY': {'Room': '氧供来源', 'The oxygen source is the room air.': '说明'},
        '60004^MNDRY_O2_SRC_MSK^99MNDRY': {'Generic Mask': '氧供来源',
                                           'The oxygen source is mask of undefined type.': '说明'},
        '60005^MNDRY_O2_SRC_MSK_AERO^99MNDRY': {'Aerosol mask': '氧供来源', 'The oxygen source is an aerosol mask.': '说明'},
        '60006^MNDRY_O2_SRC_MSK_NONREBR^99MNDRY': {'Non-rebreather mask': '氧供来源',
                                                   'The oxygen source is a non-rebreather mask.': '说明'},
        '60007^MNDRY_O2_SRC_MSK_PART_REBR^99MNDRY': {'Partial rebreather mask': '氧供来源',
                                                     'The oxygen source is a partial rebreather mask.': '说明'},
        '60008^MNDRY_O2_SRC_MSK_VENTURI^99MNDRY': {'Venturi mask': '氧供来源',
                                                   'The oxygen source is a venturi mask.': '说明'},
        '60009^MNDRY_O2_SRC_MSK_FACE_TENT^99MNDRY': {'Face tent mask': '氧供来源',
                                                     'The oxygen source is a face tent mask': '说明'},
        '60010^MNDRY_O2_SRC_MSK_BIPAP^99MNDRY': {'BiPAP': '氧供来源',
                                                 'The oxygen source is a bilevel positive airway pressure mask.': '说明'},
        '60011^MNDRY_O2_SRC_MSK_CPAP^99MNDRY': {'CPAP': '氧供来源',
                                                'The oxygen source is a continuous positive airway pressure mask.': '说明'},
        '60012^MNDRY_O2_SRC_NAS_CAN^99MNDRY': {'Nasal Cannula': '氧供来源', 'The oxygen source is a nasal cannula.': '说明'},
        '60013^MNDRY_O2_SRC_T_PIECE^99MNDRY': {'T-piece': '氧供来源', 'The oxygen source is a T-piece.': '说明'},
        '60014^MNDRY_O2_SRC_TRACH_COL^99MNDRY': {'Tracheostomy collar': '氧供来源',
                                                 'The oxygen source is a tracheostomy collar.': '说明'},
        '60015^MNDRY_O2_SRC_VENT^99MNDRY': {'Ventilator': '氧供来源', 'The oxygen source is a ventilator.': '说明'},
        '60016^MNDRY_O2_SRC_OXY^99MNDRY': {'Oxymizer': '氧供来源', 'The oxygen source is an oxymizer.': '说明'},
        '60047^MNDRY_O2_SRC_UNKNOWN^99MNDRY': {'Unknown': '氧供来源', 'The oxygen source is unknown.': '说明'},
        '60024^MNDRY_SRC_PRESS_BLD^99MNDRY': {'IBP': '来源', 'Unlabeled invasive blood pressure (IBP1- IBP8)': '说明'},
        '60025^MNDRY_SRC_PRESS_BLD_ART^99MNDRY': {'ART': '来源', 'Arterial pressure': '说明'},
        '60026^MNDRY_SRC_PRESS_BLD_ART_FEMORAL^99MNDRY': {'FAP': '来源', 'Femoral arterial pressure': '说明'},
        '60027^MNDRY_SRC_PRESS_BLD_ART_BRACHIAL^99MNDRY': {'BAP': '来源', 'Brachial arterial pressure': '说明'},
        '60028^MNDRY_SRC_PRESS_BLD_AORT^99MNDRY': {'AoP': '来源', 'Aorta pressure': '说明'},
        '60029^MNDRY_SRC_PRESS_BLD_VENT_LEFT^99MNDRY': {'LVP': '来源', 'Left ventricle pressure': '说明'},
        '60030^MNDRY_SRC_PRESS_BLD_ART_UMB^99MNDRY': {'UAP': '来源', 'Umbilical arterial pressure': '说明'},
        '60039^MNDRY_SRC_PRESS_BLD_ART_PULM^99MNDRY': {'PA': '来源', 'Pulmonary arterial pressure': '说明'},
        '60040^MNDRY_SRC_PRESS_BLD_VEN_CENT^99MNDRY': {'CVP': '来源', 'Central venous pressure': '说明'},
        '60041^MNDRY_SRC_PRESS_INTRA_CRAN^99MNDRY': {'ICP': '来源', 'Intra-cranial pressure': '说明'},
        '60042^MNDRY_SRC_PRESS_BLD_ATR_RIGHT^99MNDRY': {'RA': '来源', 'Right arterial pressure': '说明'},
        '60043^MNDRY_SRC_PRESS_BLD_ATR_LEFT^99MNDRY': {'LA': '来源', 'Left arterial pressure': '说明'},
        '30000^MNDRY_TRUE^99MNDRY': {'True': '布尔值', 'The valueis true': '说明'},
        '30001^MNDRY_FALSE^99MNDRY': {'False': '布尔值', 'The value is false': '说明'},
        '60057^MNDRY_OFF^99MNDRY': {'Off': '布尔值', 'The value is off': '说明'},
        '60058^MNDRY_ON^99MNDRY': {'On': '布尔值', 'The value is on': '说明'},
        '60050^MNDRY_ECG_QTC_FORMULA_BAZETT^99MNDRY': {'Bazett': 'QTC 公式', 'The QTc formula used is Bazett.': '说明'},
        '60051^MNDRY_ECG_QTC_FORMULA_HODGES^99MNDRY': {'Hodges': 'QTC 公式', 'The QTc formula used is Hodges.': '说明'},
        '60052^MNDRY_ECG_QTC_FORMULA_FRIDERICIA^99MNDRY': {'Fridericia': 'QTC 公式',
                                                           'The QTc formula used is Fridericia.': '说明'},
        '60053^MNDRY_ECG_QTC_FORMULA_FRAINGHAM^99MNDRY': {'Fraingham': 'QTC 公式',
                                                          'The QTc formula used is Fraingham.': '说明'},
        '60031^MNDRY_PAIN_NONE^99MNDRY': {'None': '疼痛', 'The patient has no pain.': '说明'},
        '60032^MNDRY_PAIN_MILD^99MNDRY': {'Mild': '疼痛', 'The patient has mild pain.': '说明'},
        '60033^MNDRY_PAIN_MODERATE^99MNDRY': {'Moderate': '疼痛', 'The patient has moderate pain.': '说明'},
        '60034^MNDRY_PAIN_SEVERE^99MNDRY': {'Severe': '疼痛', 'The patient has severe pain.': '说明'},
        '60046^MNDRY_PAIN_UNKNOWN^99MNDRY': {'Unknown': '疼痛', 'The patient’s pain level is not known.': '说明'},
        '60035^MNDRY_SCORE_LOC_AVPU_ALERT^99MNDRY': {'Alert': 'AVPU 评分', 'The patient is alert.': '说明'},
        '60036^MNDRY_SCORE_LOC_AVPU_VOICE^99MNDRY': {'Voice': 'AVPU 评分', 'The patient responds to voices.': '说明'},
        '60037^MNDRY_SCORE_LOC_AVPU_PAIN^99MNDRY': {'Pain': 'AVPU 评分', 'The patient responds to pain.': '说明'},
        '60038^MNDRY_SCORE_LOC_AVPU_UNRESPONSIVE^99MNDRY': {'Unresponsive': 'AVPU 评分',
                                                            'The patient is unresponsive.': '说明'},
        '60039^MNDRY_SCORE_LOC_AVPU_CONFUSED^99MNDRY': {'Confused': 'AVPU 评分', 'The patient is confused.': '说明'},
        '60045^MNDRY_SCORE_LOC_AVPU_UNKNOWN^99MNDRY': {'Unknown': 'AVPU 评分',
                                                       'The patient’s response level is not known.': '说明'},
        '50000^MNDRY_VENT_MODE_MANUAL^99MNDRY': {'Manual': '通气模式', '': '说明'},
        '50001^MNDRY_VENT_MODE_ACGO^99MNDRY': {'ACGO': '通气模式', '': '说明'},
        '50002^MNDRY_VENT_MODE_MANUAL_PLUS_ALM_OFF^99MNDRY': {'Manual, Alarms Off': '通气模式', '': '说明'},
        '50003^MNDRY_VENT_MODE_MANUAL_PLUS_BYPASS^99MNDRY': {'Manual, Bypass': '通气模式', '': '说明'},
        '50004^MNDRY_VENT_MODE_MANUAL_PLUS_MONITOR^99MNDRY': {'Manual, Monitor': '通气模式', '': '说明'},
        '50005^MNDRY_VENT_MODE_VCV^99MNDRY': {'Volume Control Ventilation': '通气模式', '': '说明'},
        '50006^MNDRY_VENT_MODE_PS^99MNDRY': {'Pressure Support Ventilation': '通气模式', '': '说明'},
        '50007^MNDRY_VENT_MODE_SIMVVC^99MNDRY': {'SIMV with Volume Control': '通气模式', '': '说明'},
        '50008^MNDRY_VENT_MODE_SIMVVC_PLUS_PS^99MNDRY': {'SIMV with Volume Control and Pressure\nSupport': '通气模式',
                                                         '': '说明'},
        '50009^MNDRY_VENT_MODE_SIMVPC^99MNDRY': {'SIMV with Pressure Control': '通气模式', '': '说明'},
        '50010^MNDRY_VENT_MODE_SIMVPC_PLUS_PS^99MNDRY': {'SIMV with Pressure Control and Pressure\nSupport': '通气模式',
                                                         '': '说明'},
        '50011^MNDRY_VENT_MODE_PCV^99MNDRY': {'Pressure Control Ventilation': '通气模式', '': '说明'},
        '50012^MNDRY_VENT_MODE_PCV_PLUS_VG^99MNDRY': {'Pressure Control Ventilation with Volume\nGuarantee': '通气模式',
                                                      '': '说明'},
        '50013^MNDRY_MODE_AVNF^99MNDRY': {'AVNF': '通气模式', '': '说明'},
        '50015^MNDRY_VENT_MODE_DUOLEVEL^99MNDRY': {'Duolevel': '通气模式', '': '说明'},
        '50017^MNDRY_VENT_MODE_APRV^99MNDRY': {'APRV': '通气模式', '': '说明'},
        '50021^MNDRY_VENT_MODE_CPAP_PLUS_PS^99MNDRY': {'CPAP with Pressure Support': '通气模式', '': '说明'},
        '50022^MNDRY_VENT_MODE_SIMVPC_PLUS_PRVC^99MNDRY': {'SIMV with Pressure Control with PRVC': '通气模式', '': '说明'},
        '50023^MNDRY_VENT_MODE_RM^99MNDRY': {'Recruitment Maneuver': '通气模式', '': '说明'},
        '50035^MNDRY_VENT_MODE_SIMVVG_PLUS_PS^99MNDRY': {'SIMV with Volume Guarantee and Pressure\nSupport': '通气模式',
                                                         '': '说明'},
        '50014^MNDRY_VENT_MODE_CPAP^99MNDRY': {'CPAP': '通气模式', '': '说明'},
        '50054^MNDRY_VENT_MODE_PACV^99MNDRY': {'Pressure Assist and Control Ventilation': '通气模式', '': '说明'},
        '50055^MNDRY_VENT_MODE_PRVC^99MNDRY': {'PRVC': '通气模式', '': '说明'},
        '50056^MNDRY_VENT_MODE_VSV^99MNDRY': {'Volume Support Ventilation': '通气模式', '': '说明'},
        '50057^MNDRY_VENT_MODE_CPRV^99MNDRY': {'Cardiopulmonary Resuscitation Ventilation': '通气模式', '': '说明'},
        '50058^MNDRY_VENT_MODE_NCPAP^99MNDRY': {'Nasal CPAP': '通气模式', '': '说明'},
        '50059^MNDRY_VENT_MODE_AMV^99MNDRY': {'AMV': '通气模式', '': '说明'},
        '50060^MNDRY_VENT_MODE_PSV_PLUS_STV^99MNDRY': {'Pressure Support Ventilation with STV': '通气模式', '': '说明'},
        '50061^MNDRY_VENT_MODE_O2_THERAPY^99MNDRY': {'O2 Therapy': '通气模式', '': '说明'},
        '50062^MNDRY_VENT_MODE_VACV^99MNDRY': {'Volume Assist and Control Ventilation': '通气模式', '': '说明'},
        '202836^MDC_EVT_STAT_STANDBY^MDC': {'Device Status:Standby/Discharge': 'Device Status:Running', '': ''},
        '30003^MNDRY_EVT_STAT_MODE_NORMAL^99MNDRY': {'Device Mode:Normal': 'Device Status:Running', '': ''},
        '202840^MDC_EVT_STAT_MODE_TEST^MDC': {'Device Mode:Service': 'Device Status:Running', '': ''},
        '30004^MNDRY_EVT_STAT_MODE_DEMO^99MNDRY': {'Device Mode:Demo': 'Device Status:Running', '': ''},
        '202890^MDC_EVT_STAT_DEV_MODE_ADULT^MDC': {'Patient Type: Adult': 'Device Status:Running', '': ''},
        '202888^MDC_EVT_STAT_DEV_MODE_PEDIATRIC^MDC': {'Patient Type: Pediatric': 'Device Status:Running', '': ''},
        '30006^MNDRY_EVT_STAT_DEV_MODE_INFANT^99MNDRY': {'Patient Type: Infant': 'Device Status:Running', '': ''},
        '60054^MNDRY_TEST_PASS^99MNDRY': {'TEST_PASS': '测试结果', 'The test passed': '说明'},
        '60055^MNDRY_TEST_FAIL^99MNDRY': {'TEST_FAIL': '测试结果', 'The test failed': '说明'},
        '60074^MNDRY_PAIN_LEVEL_TYPE_UNKNOWN^99MNDRY': {'UNKNOWN': '疼痛类型', '': '说明'},
        '60058^MNDRY_PAIN_LEVEL_TYPE_VAS_CM^99MNDRY': {'VAS_CM': '疼痛类型', '': '说明'},
        '60059^MNDRY_PAIN_LEVEL_TYPE_VAS_MM^99MNDRY': {'VAS_MM': '疼痛类型', '': '说明'},
        '60060^MNDRY_PAIN_LEVEL_TYPE_NRS^99MNDRY': {'NRS': '疼痛类型', '': '说明'},
        '60061^MNDRY_PAIN_LEVEL_TYPE_VRS_4^99MNDRY': {'VRS_4': '疼痛类型', '': '说明'},
        '60062^MNDRY_PAIN_LEVEL_TYPE_VRS_5^99MNDRY': {'VRS_5': '疼痛类型', '': '说明'},
        '60063^MNDRY_PAIN_LEVEL_TYPE_FPS_R^99MNDRY': {'FPS_R': '疼痛类型', '': '说明'},
        '60064^MNDRY_PAIN_LEVEL_TYPE_FLACC^99MNDRY': {'FLACC': '疼痛类型', '': '说明'},
        '60065^MNDRY_PAIN_LEVEL_TYPE_OTHERS^99MNDRY': {'OTHERS': '疼痛类型', '': '说明'},
        '60075^MNDRY_PAIN_LEVEL_TYPE_CUSTOM1^99MNDRY': {'CUSTOM1': '疼痛类型', '': '说明'},
        '60076^MNDRY_PAIN_LEVEL_TYPE_CUSTOM2^99MNDRY': {'CUSTOM2': '疼痛类型', '': '说明'}}
