id_col_num = 1
header = ['单位', '编码', '文本', '编码系统', "单位类型"]

data = {'264864^MDC_DIM_BEAT_PER_MIN^MDC': ['Beats*min-1', '264864', 'MDC_DIM_BEAT_PER_MIN', 'MDC', 'Rates'],
        '264928^MDC_DIM_RESP_PER_MIN^MDC': ['Respirations*min-1', '264928', 'MDC_DIM_RESP_PER_MIN', 'MDC', 'Rates'],
        '264311^MDC_DIM_PER_KILO_SEC^MDC': ['ks-1', '264311', 'MDC_DIM_PER_KILO_SEC', 'MDC', 'Rates'],
        '264672^MDC_DIM_PER_MIN^MDC': ['min-1', '264672', 'MDC_DIM_PER_MIN', 'MDC', 'Rates'],
        '264640^MDC_DIM_HZ^MDC': ['Hz', '264640', 'MDC_DIM_HZ', 'MDC', 'Rates'],
        '263264^MDC_DIM_BREATH^MDC': ['Breath', '263264', 'MDC_DIM_BREATH', 'MDC', 'Rates'],
        '263875^MDC_DIM_KILO_G^MDC': ['kilograms (kg)', '263875', 'MDC_DIM_KILO_G', 'MDC', 'Weight'],
        '263904^MDC_DIM_LB^MDC': ['pounds (lb)', '263904', 'MDC_DIM_LB', 'MDC', 'Weight'],
        '263936^MDC_DIM_OZ^MDC': ['ounces (oz)', '263936', 'MDC_DIM_OZ', 'MDC', 'Weight'],
        '263424^MDC_DIM_M^MDC': ['meters (m)', '263424', 'MDC_DIM_M', 'MDC', 'Length'],
        '263441^MDC_DIM_CENTI_M^MDC': ['centimeters (cm)', '263441', 'MDC_DIM_CENTI_M', 'MDC', 'Length'],
        '263442^MDC_DIM_MILLI_M^MDC': ['millimeters (mm)', '263442', 'MDC_DIM_MILLI_M', 'MDC', 'Length'],
        '263488^MDC_DIM_FOOT^MDC': ['feet (ft)', '263488', 'MDC_DIM_FOOT', 'MDC', 'Length'],
        '263520^MDC_DIM_INCH^MDC': ['inches (in)', '263520', 'MDC_DIM_INCH', 'MDC', 'Length'],
        '263616^MDC_DIM_SQ_M^MDC': ['meters2 (m2)', '263616', 'MDC_DIM_SQ_M', 'MDC', 'Area'],
        '263744^MDC_DIM_L^MDC': ['liters (l)', '263744', 'MDC_DIM_L', 'MDC', 'Liquid Volume'],
        '263762^MDC_DIM_MILLI_L^MDC': ['milliliters (ml)', '263762', 'MDC_DIM_MILLI_L', 'MDC', 'Liquid Volume'],
        '268192^MDC_DIM_DEGC^MDC': ['degrees Celsius (°C)', '268192', 'MDC_DIM_DEGC', 'MDC', 'Temperature'],
        '266560^MDC_DIM_FAHR^MDC': ['degrees Fahrenheit (°F)', '266560', 'MDC_DIM_FAHR', 'MDC', 'Temperature'],
        '266432^MDC_DIM_OHM^MDC': ['ohms (Ω)', '266432', 'MDC_DIM_OHM', 'MDC', 'Electrical Resistance'],
        '266450^MDC_DIM_MILLI_OHM^MDC': ['milliohms (mΩ)', '266450', 'MDC_DIM_MILLI_OHM', 'MDC',
                                         'Electrical Resistance'],
        '266435^MDC_DIM_KILLO_OHM^MDC': ['killiohms (kΩ)', '266435', 'MDC_DIM_KILLO_OHM', 'MDC',
                                         'Electrical Resistance'],
        '266400^MDC_DIM_VOLT^MDC': ['volts (V)', '266400', 'MDC_DIM_VOLT', 'MDC', 'Electrical Potential'],
        '266418^MDC_DIM_MILLI_VOLT^MDC': ['millivolts (mV)', '266418', 'MDC_DIM_MILLI_VOLT', 'MDC',
                                          'Electrical Potential'],
        '266419^MDC_DIM_MICRO_VOLT^MDC': ['microvolts (uV)', '266419', 'MDC_DIM_MICRO_VOLT', 'MDC',
                                          'Electrical Potential'],
        '265216^MDC_DIM_L_PER_MIN^MDC': ['l*min-1', '265216', 'MDC_DIM_L_PER_MIN', 'MDC', 'Flow'],
        '265234^MDC_DIM_MILLI_L_PER_MIN^MDC': ['ml*min-1', '265234', 'MDC_DIM_MILLI_L_PER_MIN', 'MDC', 'Flow'],
        '265266^MDC_DIM_MILLI_L_PER_HR^MDC': ['ml*hr-1', '265266', 'MDC_DIM_MILLI_L_PER_HR', 'MDC', 'Flow'],
        '264352^MDC_DIM_MIN^MDC': ['minutes (min)', '264352', 'MDC_DIM_MIN', 'MDC', 'Time'],
        '264320^MDC_DIM_SEC^MDC': ['seconds (s)', '264320', 'MDC_DIM_SEC', 'MDC', 'Time'],
        '264338^MDC_DIM_MILLI_SEC^MDC': ['milliseconds (ms)', '264338', 'MDC_DIM_MILLI_SEC', 'MDC', 'Time'],
        '266016^MDC_DIM_MMHG^MDC': ['mmHg', '266016', 'MDC_DIM_MMHG', 'MDC', 'Pressure'],
        '266048^MDC_DIM_CM_H2O^MDC': ['cmH2O', '266048', 'MDC_DIM_CM_H2O', 'MDC', 'Pressure'],
        '265987^MDC_DIM_KILO_PASCAL^MDC': ['kilopascal (kPa)', '265987', 'MDC_DIM_KILO_PASCAL', 'MDC', 'Pressure'],
        '265986^MDC_DIM_HECTO_PASCAL^MDC': ['hectopascal (hPa)', '265986', 'MDC_DIM_HECTO_PASCAL', 'MDC', 'Pressure'],
        '266098^MDC_DIM_MILLI_BAR^MDC': ['millibar', '266098', 'MDC_DIM_MILLI_BAR', 'MDC', 'Pressure'],
        '266176^MDC_DIM_WATT^MDC': ['Watts (W)', '266176', 'MDC_DIM_WATT', 'MDC', 'Power'],
        '266194^MDC_DIM_MILLI_WATT^MDC': ['milliwatts (mW)', '266194', 'MDC_DIM_MILLI_WATT', 'MDC', 'Power'],
        '268224^MDC_DIM_AMP_HR^MDC': ['ampere hour (Ah)', '268224', 'MDC_DIM_AMP_HR', 'MDC', 'Electrical Charge'],
        '268242^MDC_DIM_MILLI_AMP_HR^MDC': ['milliampere hour (mAh)', '268242', 'MDC_DIM_MILLI_AMP_HR', 'MDC',
                                            'Electrical Charge'],
        '264000^MDC_DIM_G_M^MDC': ['g*m', '264000', 'MDC_DIM_G_M', 'MDC', 'Work'],
        '264992^MDC_DIM_L_PER_MIN_PER_M_SQ^MDC': ['l*min-1*m-2', '264992', 'MDC_DIM_L_PER_MIN_PER_M_SQ', 'MDC',
                                                  'Miscellaneous'],
        '265010^MDC_DIM_MILLI_L_PER_MIN_PER_M_SQ^MDC': ['ml*min-1*m-2', '265010', 'MDC_DIM_MILLI_L_PER_MIN_PER_M_SQ',
                                                        'MDC', 'Miscellaneous'],
        '268160^MDC_DIM_DYNE_SEC_PER_M_SQ_PER_CM_5^MDC': ['dyne*s*m-2*cm-5', '268160',
                                                          'MDC_DIM_DYNE_SEC_PER_M_SQ_PER_CM_5', 'MDC', 'Miscellaneous'],
        '268064^MDC_DIM_CM_H2O_PER_L_PER_SEC^MDC': ['cmH2O*l-1*s-1', '268064', 'MDC_DIM_CM_H2O_PER_L_PER_SEC', 'MDC',
                                                    'Miscellaneous'],
        '268288^MDC_DIM_CM_H2O_PER_L^MDC': ['cmH2O*l-1', '268288', 'MDC_DIM_CM_H2O_PER_L', 'MDC', 'Miscellaneous'],
        '262688^MDC_DIM_PERCENT^MDC': ['%', '262688', 'MDC_DIM_PERCENT', 'MDC', 'Miscellaneous'],
        '268576^MDC_DIM_DECIBEL^MDC': ['dB', '268576', 'MDC_DIM_DECIBEL', 'MDC', 'Miscellaneous'],
        '263570^MDC_DIM_MILLI_L_PER_M_SQ^MDC': ['ml*m-2', '263570', 'MDC_DIM_MILLI_L_PER_M_SQ', 'MDC', 'Miscellaneous'],
        '264032^MDC_DIM_G_M_PER_M_SQ^MDC': ['g*m*m-2', '264032', 'MDC_DIM_G_M_PER_M_SQ', 'MDC', 'Miscellaneous'],
        '264035^MDC_DIM_KILO_G_M_PER_M_SQ^MDC': ['kg*m*m-2', '264035', 'MDC_DIM_KILO_G_M_PER_M_SQ', 'MDC',
                                                 'Miscellaneous'],
        '264256^MDC_DIM_G_PER_DL^MDC': ['g*dl-1', '264256', 'MDC_DIM_G_PER_DL', 'MDC', 'Miscellaneous'],
        '266866^MDC_DIM_MILLI_MOLE_PER_L^MDC': ['mmol*l-1', '266866', 'MDC_DIM_MILLI_MOLE_PER_L', 'MDC',
                                                'Miscellaneous'],
        '263584^MDC_DIM_PER_M^MDC': ['m-1', '263584', 'MDC_DIM_PER_M', 'MDC', 'Miscellaneous'],
        '263602^MDC_DIM_PER_MILLI_M^MDC': ['mm-1', '263602', 'MDC_DIM_PER_MILLI_M', 'MDC', 'Miscellaneous'],
        '268672^MDC_PER_L_PER_MIN^MDC': ['l-1*min-1', '268672', 'MDC_PER_L_PER_MIN', 'MDC', 'Miscellaneous'],
        '265312^MDC_DIM_L_PER_KG^MDC': ['l*kg-1', '265312', 'MDC_DIM_L_PER_KG', 'MDC', 'Miscellaneous'],
        '265330^MDC_DIM_MILLI_L_PER_KG^MDC': ['ml*kg-1', '265330', 'MDC_DIM_MILLI_L_PER_KG', 'MDC', 'Miscellaneous'],
        '270656^MDC_DIM_DYNE_SEC_PER_CM_5^MDC': ['dyne*sec*cm-5', '270656', 'MDC_DIM_DYNE_SEC_PER_CM_5', 'MDC',
                                                 'Miscellaneous'],
        '270563^MDC_DIM_KILO_CAL_PER_DAY^MDC': ['kcal*day-1', '270563', 'MDC_DIM_KILO_CAL_PER_DAY', 'MDC',
                                                'Miscellaneous'],
        '270930^MDC_DIM_MILLI_L_PER_MIN_PER_KG^MDC': ['ml*min-1*kg-1', '270930', 'MDC_DIM_MILLI_L_PER_MIN_PER_KG',
                                                      'MDC', 'Miscellaneous'],
        '270624^MDC_DIM_JOULES_PER_L^MDC': ['J*l-1', '270624', 'MDC_DIM_JOULES_PER_L', 'MDC', 'Miscellaneous'],
        '270435^MDC_DIM_PER_KILO_OHM^MDC': ['kΩ-1', '270435', 'MDC_DIM_PER_KILO_OHM', 'MDC', 'Miscellaneous'],
        '270848^MDC_DIM_BREATHS_PER_MIN_PER_L^MDC': ['Respirations*min-1*l-1', '270848',
                                                     'MDC_DIM_BREATHS_PER_MIN_PER_L', 'MDC', 'Miscellaneous'],
        '270944^MDC_DIM_O2_SAT_PERCENT_SEC^MDC': ['%*sec', '270944', 'MDC_DIM_O2_SAT_PERCENT_SEC', 'MDC',
                                                  'Miscellaneous'],
        '268480^MDC_DIM_MM_HG_PER_L^MDC': ['mmHg*l-1', '268480', 'MDC_DIM_MM_HG_PER_L', 'MDC', 'Miscellaneous'],
        '272739^MDC_DIM_KILO_PASCAL_PER_L^MDC': ['kPa*l-1', '272739', 'MDC_DIM_KILO_PASCAL_PER_L', 'MDC',
                                                 'Miscellaneous'],
        '263892^MDC_DIM_NANO_G^MDC': ['ng', '263892', 'MDC_DIM_NANO_G', 'MDC', 'Miscellaneous'],
        '263891^MDC_DIM_MICRO_G^MDC': ['ug', '263891', 'MDC_DIM_MICRO_G', 'MDC', 'Miscellaneous'],
        '263890^MDC_DIM_MILLI_G^MDC': ['mg', '263890', 'MDC_DIM_MILLI_G', 'MDC', 'Miscellaneous'],
        '263872^MDC_DIM_G^MDC': ['g', '263872', 'MDC_DIM_G', 'MDC', 'Miscellaneous'],
        '267636^MDC_DIM_MILLI_INTL_UNIT^MDC': ['mU', '267636', 'MDC_DIM_MILLI_INTL_UNIT', 'MDC', 'Miscellaneous'],
        '267616^MDC_DIM_INTL_UNIT^MDC': ['U', '267616', 'MDC_DIM_INTL_UNIT', 'MDC', 'Miscellaneous'],
        '267619^MDC_DIM_KILO_INTL_UNIT^MDC': ['kU', '267619', 'MDC_DIM_KILO_INTL_UNIT', 'MDC', 'Miscellaneous'],
        '267620^MDC_DIM_MEGA_INTL_UNIT^MDC': ['EU', '267620', 'MDC_DIM_MEGA_INTL_UNIT', 'MDC', 'Miscellaneous'],
        '266706^MDC_DIM_MILLI_MOLE^MDC': ['mmol', '266706', 'MDC_DIM_MILLI_MOLE', 'MDC', 'Miscellaneous'],
        '266688^MDC_DIM_MOLE^MDC': ['mol', '266688', 'MDC_DIM_MOLE', 'MDC', 'Miscellaneous'],
        '270499^MDC_DIM_KILO_CAL^MDC': ['kcal', '270499', 'MDC_DIM_KILO_CAL', 'MDC', 'Miscellaneous'],
        '266738^MDC_DIM_MILLI_EQUIV^MDC': ['mEq', '266738', 'MDC_DIM_MILLI_EQUIV', 'MDC', 'Miscellaneous'],
        '264308^MDC_DIM_NANO_G_PER_ML^MDC': ['ng/ml', '264308', 'MDC_DIM_NANO_G_PER_ML', 'MDC', 'Miscellaneous'],
        '264307^MDC_DIM_MICRO_G_PER_ML^MDC': ['ug/ml', '264307', 'MDC_DIM_MICRO_G_PER_ML', 'MDC', 'Miscellaneous'],
        '264306^MDC_DIM_MILLI_G_PER_ML^MDC': ['mg/ml', '264306', 'MDC_DIM_MILLI_G_PER_ML', 'MDC', 'Miscellaneous'],
        '264288^MDC_DIM_G_PER_ML^MDC': ['g/ml', '264288', 'MDC_DIM_G_PER_ML', 'MDC', 'Miscellaneous'],
        '267762^MDC_DIM_MILLI_INTL_UNIT_PER_ML^MDC': ['mU/ml', '267762', 'MDC_DIM_MILLI_INTL_UNIT_PER_ML', 'MDC',
                                                      'Miscellaneous'],
        '267744^MDC_DIM_INTL_UNIT_PER_ML^MDC': ['U/ml', '267744', 'MDC_DIM_INTL_UNIT_PER_ML', 'MDC', 'Miscellaneous'],
        '267747^MDC_DIM_KILO_INTL_UNIT_PER_ML^MDC': ['kU/ml', '267747', 'MDC_DIM_KILO_INTL_UNIT_PER_ML', 'MDC',
                                                     'Miscellaneous'],
        '267748^MDC_DIM_MEGA_INTL_UNIT_PER_ML^MDC': ['EU/ml', '267748', 'MDC_DIM_MEGA_INTL_UNIT_PER_ML', 'MDC',
                                                     'Miscellaneous'],
        '266898^MDC_DIM_MILLI_MOLE_PER_ML^MDC': ['mmol/ml', '266898', 'MDC_DIM_MILLI_MOLE_PER_ML', 'MDC',
                                                 'Miscellaneous'],
        '266880^MDC_DIM_MOLE_PER_ML^MDC': ['mol/ml', '266880', 'MDC_DIM_MOLE_PER_ML', 'MDC', 'Miscellaneous'],
        '271171^MDC_DIM_KILO_CAL_PER_ML^MDC': ['kcal/ml', '271171', 'MDC_DIM_KILO_CAL_PER_ML', 'MDC', 'Miscellaneous'],
        '267026^MDC_DIM_MILLI_EQUIV_PER_ML^MDC': ['mEq/ml', '267026', 'MDC_DIM_MILLI_EQUIV_PER_ML', 'MDC',
                                                  'Miscellaneous'],
        '265620^MDC_DIM_NANO_G_PER_KG_PER_MIN^MDC': ['ng/kg/min', '265620', 'MDC_DIM_NANO_G_PER_KG_PER_MIN', 'MDC',
                                                     'Miscellaneous'],
        '265652^MDC_DIM_NANO_G_PER_KG_PER_HR^MDC': ['ng/kg/hour', '265652', 'MDC_DIM_NANO_G_PER_KG_PER_HR', 'MDC',
                                                    'Miscellaneous'],
        '265684^MDC_DIM_NANO_G_PER_KG_PER_DAY^MDC': ['ng/kg/day', '265684', 'MDC_DIM_NANO_G_PER_KG_PER_DAY', 'MDC',
                                                     'Miscellaneous'],
        '265619^MDC_DIM_MICRO_G_PER_KG_PER_MIN^MDC': ['ug/kg/min', '265619', 'MDC_DIM_MICRO_G_PER_KG_PER_MIN', 'MDC',
                                                      'Miscellaneous'],
        '265651^MDC_DIM_MICRO_G_PER_KG_PER_HR^MDC': ['ug/kg/hour', '265651', 'MDC_DIM_MICRO_G_PER_KG_PER_HR', 'MDC',
                                                     'Miscellaneous'],
        '265683^MDC_DIM_MICRO_G_PER_KG_PER_DAY^MDC': ['ug/kg/day', '265683', 'MDC_DIM_MICRO_G_PER_KG_PER_DAY', 'MDC',
                                                      'Miscellaneous'],
        '265618^MDC_DIM_MILLI_G_PER_KG_PER_MIN^MDC': ['mg/kg/min', '265618', 'MDC_DIM_MILLI_G_PER_KG_PER_MIN', 'MDC',
                                                      'Miscellaneous'],
        '265650^MDC_DIM_MILLI_G_PER_KG_PER_HR^MDC': ['mg/kg/hour', '265650', 'MDC_DIM_MILLI_G_PER_KG_PER_HR', 'MDC',
                                                     'Miscellaneous'],
        '265682^MDC_DIM_MILLI_G_PER_KG_PER_DAY^MDC': ['mg/kg/day', '265682', 'MDC_DIM_MILLI_G_PER_KG_PER_DAY', 'MDC',
                                                      'Miscellaneous'],
        '265600^MDC_DIM_G_PER_KG_PER_MIN^MDC': ['g/kg/min', '265600', 'MDC_DIM_G_PER_KG_PER_MIN', 'MDC',
                                                'Miscellaneous'],
        '265632^MDC_DIM_G_PER_KG_PER_HR^MDC': ['g/kg/hour', '265632', 'MDC_DIM_G_PER_KG_PER_HR', 'MDC',
                                               'Miscellaneous'],
        '265664^MDC_DIM_G_PER_KG_PER_DAY^MDC': ['g/kg/day', '265664', 'MDC_DIM_G_PER_KG_PER_DAY', 'MDC',
                                                'Miscellaneous'],
        '267954^MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_MIN^MDC': ['mU/kg/min', '267954',
                                                              'MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_MIN', 'MDC',
                                                              'Miscellaneous'],
        '267986^MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_HR^MDC': ['mU/kg/hour', '267986',
                                                             'MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_HR', 'MDC',
                                                             'Miscellaneous'],
        '268018^MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_DAY^MDC': ['mU/kg/day', '268018',
                                                              'MDC_DIM_MILLI_INTL_UNIT_PER_KG_PER_DAY', 'MDC',
                                                              'Miscellaneous'],
        '267936^MDC_DIM_INTL_UNIT_PER_KG_PER_MIN^MDC': ['U/kg/min', '267936', 'MDC_DIM_INTL_UNIT_PER_KG_PER_MIN', 'MDC',
                                                        'Miscellaneous'],
        '267968^MDC_DIM_INTL_UNIT_PER_KG_PER_HR^MDC': ['U/kg/hour', '267968', 'MDC_DIM_INTL_UNIT_PER_KG_PER_HR', 'MDC',
                                                       'Miscellaneous'],
        '268000^MDC_DIM_INTL_UNIT_PER_KG_PER_DAY^MDC': ['U/kg/day', '268000', 'MDC_DIM_INTL_UNIT_PER_KG_PER_DAY', 'MDC',
                                                        'Miscellaneous'],
        '267971^MDC_DIM_KILO_INTL_UNIT_PER_KG_PER_HR^MDC': ['kU/kg/hour', '267971',
                                                            'MDC_DIM_KILO_INTL_UNIT_PER_KG_PER_HR', 'MDC',
                                                            'Miscellaneous'],
        '268003^MDC_DIM_KILO_INTL_UNIT_PER_KG_PER_DAY^MDC': ['kU/kg/day', '268003',
                                                             'MDC_DIM_KILO_INTL_UNIT_PER_KG_PER_DAY', 'MDC',
                                                             'Miscellaneous'],
        '267972^MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_HR^MDC': ['EU/kg/hour', '267972',
                                                            'MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_HR', 'MDC',
                                                            'Miscellaneous'],
        '268004^MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_DAY^MDC': ['EU/kg/day', '268004',
                                                             'MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_DAY', 'MDC',
                                                             'Miscellaneous'],
        '267410^MDC_DIM_MILLI_MOLE_PER_KG_PER_MIN^MDC': ['mmol/kg/min', '267410', 'MDC_DIM_MILLI_MOLE_PER_KG_PER_MIN',
                                                         'MDC', 'Miscellaneous'],
        '267442^MDC_DIM_MILLI_MOLE_PER_KG_PER_HR^MDC': ['mmol/kg/hour', '267442', 'MDC_DIM_MILLI_MOLE_PER_KG_PER_HR',
                                                        'MDC', 'Miscellaneous'],
        '267474^MDC_DIM_MILLI_MOLE_PER_KG_PER_DAY^MDC': ['mmol/kg/day', '267474', 'MDC_DIM_MILLI_MOLE_PER_KG_PER_DAY',
                                                         'MDC', 'Miscellaneous'],
        '267424^MDC_DIM_MOLE_PER_KG_PER_HR^MDC': ['mol/kg/hour', '267424', 'MDC_DIM_MOLE_PER_KG_PER_HR', 'MDC',
                                                  'Miscellaneous'],
        '271139^MDC_DIM_KILO_CAL_PER_KG_PER_DAY^MDC': ['kcal/kg/day', '271139', 'MDC_DIM_KILO_CAL_PER_KG_PER_DAY',
                                                       'MDC', 'Miscellaneous'],
        '267538^MDC_DIM_MILLI_EQUIV_PER_KG_PER_MIN^MDC': ['mEq/kg/min', '267538', 'MDC_DIM_MILLI_EQUIV_PER_KG_PER_MIN',
                                                          'MDC', 'Miscellaneous'],
        '267570^MDC_DIM_MILLI_EQUIV_PER_KG_PER_HR^MDC': ['mEq/kg/hour', '267570', 'MDC_DIM_MILLI_EQUIV_PER_KG_PER_HR',
                                                         'MDC', 'Miscellaneous'],
        '267602^MDC_DIM_MILLI_EQUIV_PER_KG_PER_DAY^MDC': ['mEq/kg/day', '267602', 'MDC_DIM_MILLI_EQUIV_PER_KG_PER_DAY',
                                                          'MDC', 'Miscellaneous'],
        '265492^MDC_DIM_NANO_G_PER_MIN^MDC': ['ng/min', '265492', 'MDC_DIM_NANO_G_PER_MIN', 'MDC', 'Miscellaneous'],
        '265524^MDC_DIM_NANO_G_PER_HR^MDC': ['ng/hour', '265524', 'MDC_DIM_NANO_G_PER_HR', 'MDC', 'Miscellaneous'],
        '265556^MDC_DIM_NANO_G_PER_DAY^MDC': ['ng/day', '265556', 'MDC_DIM_NANO_G_PER_DAY', 'MDC', 'Miscellaneous'],
        '265491^MDC_DIM_MICRO_G_PER_MIN^MDC': ['ug/min', '265491', 'MDC_DIM_MICRO_G_PER_MIN', 'MDC', 'Miscellaneous'],
        '265523^MDC_DIM_MICRO_G_PER_HR^MDC': ['ug/hour', '265523', 'MDC_DIM_MICRO_G_PER_HR', 'MDC', 'Miscellaneous'],
        '265555^MDC_DIM_MICRO_G_PER_DAY^MDC': ['ug/day', '265555', 'MDC_DIM_MICRO_G_PER_DAY', 'MDC', 'Miscellaneous'],
        '265490^MDC_DIM_MILLI_G_PER_MIN^MDC': ['mg/min', '265490', 'MDC_DIM_MILLI_G_PER_MIN', 'MDC', 'Miscellaneous'],
        '265522^MDC_DIM_MILLI_G_PER_HR^MDC': ['mg/hour', '265522', 'MDC_DIM_MILLI_G_PER_HR', 'MDC', 'Miscellaneous'],
        '265554^MDC_DIM_MILLI_G_PER_DAY^MDC': ['mg/day', '265554', 'MDC_DIM_MILLI_G_PER_DAY', 'MDC', 'Miscellaneous'],
        '265472^MDC_DIM_G_PER_MIN^MDC': ['g/min', '265472', 'MDC_DIM_G_PER_MIN', 'MDC', 'Miscellaneous'],
        '265504^MDC_DIM_G_PER_HR^MDC': ['g/hour', '265504', 'MDC_DIM_G_PER_HR', 'MDC', 'Miscellaneous'],
        '265536^MDC_DIM_G_PER_DAY^MDC': ['g/day', '265536', 'MDC_DIM_G_PER_DAY', 'MDC', 'Miscellaneous'],
        '267826^MDC_DIM_MILLI_INTL_UNIT_PER_MIN^MDC': ['mU/min', '267826', 'MDC_DIM_MILLI_INTL_UNIT_PER_MIN', 'MDC',
                                                       'Miscellaneous'],
        '267858^MDC_DIM_MILLI_INTL_UNIT_PER_HR^MDC': ['mU/hour', '267858', 'MDC_DIM_MILLI_INTL_UNIT_PER_HR', 'MDC',
                                                      'Miscellaneous'],
        '267890^MDC_DIM_MILLI_INTL_UNIT_PER_DAY^MDC': ['mU/day', '267890', 'MDC_DIM_MILLI_INTL_UNIT_PER_DAY', 'MDC',
                                                       'Miscellaneous'],
        '267808^MDC_DIM_INTL_UNIT_PER_MIN^MDC': ['U/min', '267808', 'MDC_DIM_INTL_UNIT_PER_MIN', 'MDC',
                                                 'Miscellaneous'],
        '267840^MDC_DIM_INTL_UNIT_PER_HR^MDC': ['U/hour', '267840', 'MDC_DIM_INTL_UNIT_PER_HR', 'MDC', 'Miscellaneous'],
        '267872^MDC_DIM_INTL_UNIT_PER_DAY^MDC': ['U/day', '267872', 'MDC_DIM_INTL_UNIT_PER_DAY', 'MDC',
                                                 'Miscellaneous'],
        '267843^MDC_DIM_KILO_INTL_UNIT_PER_HR^MDC': ['kU/hour', '267843', 'MDC_DIM_KILO_INTL_UNIT_PER_HR', 'MDC',
                                                     'Miscellaneous'],
        '267875^MDC_DIM_KILO_INTL_UNIT_PER_DAY^MDC': ['kU/day', '267875', 'MDC_DIM_KILO_INTL_UNIT_PER_DAY', 'MDC',
                                                      'Miscellaneous'],
        '267844^MDC_DIM_MEGA_INTL_UNIT_PER_HR^MDC': ['EU/hour', '267844', 'MDC_DIM_MEGA_INTL_UNIT_PER_HR', 'MDC',
                                                     'Miscellaneous'],
        '267876^MDC_DIM_MEGA_INTL_UNIT_PER_DAY^MDC': ['EU/day', '267876', 'MDC_DIM_MEGA_INTL_UNIT_PER_DAY', 'MDC',
                                                      'Miscellaneous'],
        '267154^MDC_DIM_MILLI_MOLE_PER_MIN^MDC': ['mmol/min', '267154', 'MDC_DIM_MILLI_MOLE_PER_MIN', 'MDC',
                                                  'Miscellaneous'],
        '267186^MDC_DIM_MILLI_MOLE_PER_HR^MDC': ['mmol/hour', '267186', 'MDC_DIM_MILLI_MOLE_PER_HR', 'MDC',
                                                 'Miscellaneous'],
        '267218^MDC_DIM_MILLI_MOLE_PER_DAY^MDC': ['mmol/day', '267218', 'MDC_DIM_MILLI_MOLE_PER_DAY', 'MDC',
                                                  'Miscellaneous'],
        '267168^MDC_DIM_MOLE_PER_HR^MDC': ['mol/hour', '267168', 'MDC_DIM_MOLE_PER_HR', 'MDC', 'Miscellaneous'],
        '267282^MDC_DIM_MILLI_EQUIV_PER_MIN^MDC': ['mEq/min', '267282', 'MDC_DIM_MILLI_EQUIV_PER_MIN', 'MDC',
                                                   'Miscellaneous'],
        '267314^MDC_DIM_MILLI_EQUIV_PER_HR^MDC': ['mEq/hour', '267314', 'MDC_DIM_MILLI_EQUIV_PER_HR', 'MDC',
                                                  'Miscellaneous'],
        '267346^MDC_DIM_MILLI_EQUIV_PER_DAY^MDC': ['mEq/day', '267346', 'MDC_DIM_MILLI_EQUIV_PER_DAY', 'MDC',
                                                   'Miscellaneous'],
        '267811^MDC_DIM_KILO_INTL_UNIT_PER_MIN^MDC': ['kU/min', '267811', 'MDC_DIM_KILO_INTL_UNIT_PER_MIN', 'MDC',
                                                      'Miscellaneous'],
        '267812^MDC_DIM_MEGA_INTL_UNIT_PER_MIN^MDC': ['EU/min', '267812', 'MDC_DIM_MEGA_INTL_UNIT_PER_MIN', 'MDC',
                                                      'Miscellaneous'],
        '267136^MDC_DIM_MOLE_PER_MIN^MDC': ['mol/min', '267136', 'MDC_DIM_MOLE_PER_MIN', 'MDC', 'Miscellaneous'],
        '267200^MDC_DIM_MOLE_PER_DAY^MDC': ['mol/day', '267200', 'MDC_DIM_MOLE_PER_DAY', 'MDC', 'Miscellaneous'],
        '270578^MDC_DIM_MILLI_CAL_PER_DAY^MDC': ['mcal/day', '270578', 'MDC_DIM_MILLI_CAL_PER_DAY', 'MDC',
                                                 'Miscellaneous'],
        '270560^MDC_DIM_CAL_PER_DAY^MDC': ['cal/day', '270560', 'MDC_DIM_CAL_PER_DAY', 'MDC', 'Miscellaneous'],
        '267939^MDC_DIM_KILO_INTL_UNIT_PER_KG_PER_MIN^MDC': ['kU/kg/min', '267939',
                                                             'MDC_DIM_KILO_INTL_UNIT_PER_KG_PER_MIN', 'MDC',
                                                             'Miscellaneous'],
        '267940^MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_MIN^MDC': ['EU/kg/min', '267940',
                                                             'MDC_DIM_MEGA_INTL_UNIT_PER_KG_PER_MIN', 'MDC',
                                                             'Miscellaneous'],
        '267392^MDC_DIM_MOLE_PER_KG_PER_MIN^MDC': ['mol/kg/min', '267392', 'MDC_DIM_MOLE_PER_KG_PER_MIN', 'MDC',
                                                   'Miscellaneous'],
        '267456^MDC_DIM_MOLE_PER_KG_PER_DAY^MDC': ['mol/kg/day', '267456', 'MDC_DIM_MOLE_PER_KG_PER_DAY', 'MDC',
                                                   'Miscellaneous'],
        '271154^MNDRY_DIM_MILLI_CAL_PER_KG_PER_DAY^MDC': ['mcal/kg/day', '271154', 'MNDRY_DIM_MILLI_CAL_PER_KG_PER_DAY',
                                                          'MDC', 'Miscellaneous'],
        '271136^MNDRY_DIM_CAL_PER_KG_PER_DAY^MDC': ['cal/kg/day', '271136', 'MNDRY_DIM_CAL_PER_KG_PER_DAY', 'MDC',
                                                    'Miscellaneous'],
        '270514^MDC_DIM_MILLI_CAL^MDC': ['mcal', '270514', 'MDC_DIM_MILLI_CAL', 'MDC', 'Miscellaneous'],
        '270496^MDC_DIM_CAL^MDC': ['cal', '270496', 'MDC_DIM_CAL', 'MDC', 'Miscellaneous'],
        '271186^MDC_DIM_MILLI_CAL_PER_ML^MDC': ['mcal/ml', '271186', 'MDC_DIM_MILLI_CAL_PER_ML', 'MDC',
                                                'Miscellaneous'],
        '271168^MDC_DIM_CAL_PER_ML^MDC': ['cal/ml', '271168', 'MDC_DIM_CAL_PER_ML', 'MDC', 'Miscellaneous'],
        '10001^MNDRY_DIM_MIN_PERCENT^99MNDRY': ['minutes*%', '10001', 'MNDRY_DIM_MIN_PERCENT', '99MNDRY',
                                                'Miscellaneous'],
        '10002^MNDRY_DIM_MILLI_L_PER_MILLI_BAR^99MNDRY': ['ml*mbar-1', '10002', 'MNDRY_DIM_MILLI_L_PER_MILLI_BAR',
                                                          '99MNDRY', 'Miscellaneous'],
        '10003^MNDRY_DIM_MILLI_BAR_PER_L_PER_SEC^99MNDRY': ['mbar*l-1*s-1', '10003',
                                                            'MNDRY_DIM_MILLI_BAR_PER_L_PER_SEC', '99MNDRY',
                                                            'Miscellaneous'],
        '10005^MNDRY_DIM_CM_H2O_SEC^99MNDRY': ['cmH2O*s', '10005', 'MNDRY_DIM_CM_H2O_SEC', '99MNDRY', 'Miscellaneous'],
        '10007^MNDRY_DIM_MILLI_L_PER_HECTO_PASCAL^99MNDRY': ['ml*hPa-1', '10007', 'MNDRY_DIM_MILLI_L_PER_HECTO_PASCAL',
                                                             '99MNDRY', 'Miscellaneous'],
        '10008^MNDRY_DIM_HECTO_PASCAL_PER_L_PER_SEC^99MNDRY': ['hPa*l-1*s-1', '10008',
                                                               'MNDRY_DIM_HECTO_PASCAL_PER_L_PER_SEC', '99MNDRY',
                                                               'Miscellaneous'],
        '10010^MNDRY_DIM_JOULES_PER_MIN^99MNDRY': ['J*min-1', '10010', 'MNDRY_DIM_JOULES_PER_MIN', '99MNDRY',
                                                   'Miscellaneous'],
        '10012^MNDRY_DIM_PER_HUNDRED_PER_SEC_SQ^99MNDRY': ['100-1s-2', '10012', 'MNDRY_DIM_PER_HUNDRED_PER_SEC_SQ',
                                                           '99MNDRY', 'Miscellaneous'],
        '10013^MNDRY_DIM_WATT_PER_MIN_SQ^99MNDRY': ['W*min-2', '10013', 'MNDRY_DIM_WATT_PER_MIN_SQ', '99MNDRY',
                                                    'Miscellaneous'],
        '10014^MNDRY_DIM_MMHG_PER_SEC^99MNDRY': ['mmHg*s-1', '10014', 'MNDRY_DIM_MMHG_PER_SEC', '99MNDRY',
                                                 'Miscellaneous'],
        '10016^MNDRY_DIM_KILO_PASCAL_SEC_PER_L^99MNDRY': ['kPa*s*l-1', '10016', 'MNDRY_DIM_KILO_PASCAL_SEC_PER_L',
                                                          '99MNDRY', 'Miscellaneous'],
        '10017^MNDRY_DIM_KILO_PASCAL_SEC_M_SQ_PER_L^99MNDRY': ['kPa*s*m2*l-1', '10017',
                                                               'MNDRY_DIM_KILO_PASCAL_SEC_M_SQ_PER_L', '99MNDRY',
                                                               'Miscellaneous'],
        '10018^MNDRY_DIM_MILLI_BAR_PER_SEC^99MNDRY': ['mbar*s-1', '10018', 'MNDRY_DIM_MILLI_BAR_PER_SEC', '99MNDRY',
                                                      'Miscellaneous'],
        '10019^MNDRY_DIM_HECTO_PASCAL_SEC^99MNDRY': ['hPa*s', '10019', 'MNDRY_DIM_HECTO_PASCAL_SEC', '99MNDRY',
                                                     'Miscellaneous'],
        '10020^MNDRY_DIM_MILLI_L_PER_LB^99MNDRY': ['ml*lb-1', '10020', 'MNDRY_DIM_MILLI_L_PER_LB', '99MNDRY',
                                                   'Miscellaneous'],
        '10021^MNDRY_DIM_CM_H20_PER_SEC^99MNDRY': ['cmH2O*s-1', '10021', 'MNDRY_DIM_CM_H20_PER_SEC', '99MNDRY',
                                                   'Miscellaneous'],
        '10035^MNDRY_DIM_MILLI_BAR_SEC_PER_MIN^99MNDRY': ['Mbar*s/min', '10035', 'MNDRY_DIM_MILLI_BAR_SEC_PER_MIN',
                                                          '99MNDRY', 'Miscellaneous'],
        '10036^MNDRY_DIM_HECTO_PASCAL_SEC_PER_MIN^99MNDRY': ['hPa*s/min', '10036', 'MNDRY_DIM_HECTO_PASCAL_SEC_PER_MIN',
                                                             '99MNDRY', 'Miscellaneous'],
        '10037^MNDRY_DIM_CM_H2O_SEC_PER_MIN^99MNDRY': ['cmH2O*s/min', '10037', 'MNDRY_DIM_CM_H2O_SEC_PER_MIN',
                                                       '99MNDRY', 'Miscellaneous'],
        '10038^MNDRY_DIM_KILO_CAL_PER_KG_PER_HR^99MNDRY': ['kcal/kg/hour', '10038', 'MNDRY_DIM_KILO_CAL_PER_KG_PER_HR',
                                                           '99MNDRY', 'Miscellaneous'],
        '10038^MNDRY_DIM_KILO_CAL_PER_HR^99MNDRY': ['kcal/hour', '10038', 'MNDRY_DIM_KILO_CAL_PER_HR', '99MNDRY',
                                                    'Miscellaneous'],
        '10039^MNDRY_DIM_KILO_CAL_PER_MIN^99MNDRY': ['kcal/min', '10039', 'MNDRY_DIM_KILO_CAL_PER_MIN', '99MNDRY',
                                                     'Miscellaneous'],
        '10040^MNDRY_DIM_MILLI_CAL_PER_MIN^99MNDRY': ['mcal/min', '10040', 'MNDRY_DIM_MILLI_CAL_PER_MIN', '99MNDRY',
                                                      'Miscellaneous'],
        '10041^MNDRY_DIM_MILLI_CAL_PER_HR^99MNDRY': ['mcal/hour', '10041', 'MNDRY_DIM_MILLI_CAL_PER_HR', '99MNDRY',
                                                     'Miscellaneous'],
        '10042^MNDRY_DIM_CAL_PER_MIN^99MNDRY': ['cal/min', '10042', 'MNDRY_DIM_CAL_PER_MIN', '99MNDRY',
                                                'Miscellaneous'],
        '10043^MNDRY_DIM_CAL_PER_HR^99MNDRY': ['cal/hour', '10043', 'MNDRY_DIM_CAL_PER_HR', '99MNDRY', 'Miscellaneous'],
        '10044^MNDRY_DIM_MILLI_CAL_PER_KG_PER_MIN^99MNDRY': ['mcal/kg/min', '10044',
                                                             'MNDRY_DIM_MILLI_CAL_PER_KG_PER_MIN', '99MNDRY',
                                                             'Miscellaneous'],
        '10045^MNDRY_DIM_MILLI_CAL_PER_KG_PER_HR^99MNDRY': ['mcal/kg/hour', '10045',
                                                            'MNDRY_DIM_MILLI_CAL_PER_KG_PER_HR', '99MNDRY',
                                                            'Miscellaneous'],
        '10046^MNDRY_DIM_CAL_PER_KG_PER_MIN^99MNDRY': ['cal/kg/min', '10046', 'MNDRY_DIM_CAL_PER_KG_PER_MIN', '99MNDRY',
                                                       'Miscellaneous'],
        '10047^MNDRY_DIM_CAL_PER_KG_PER_HR^99MNDRY': ['cal/kg/hour', '10047', 'MNDRY_DIM_CAL_PER_KG_PER_HR', '99MNDRY',
                                                      'Miscellaneous'],
        '10048^MNDRY_DIM_KILO_CAL_PER_KG_PER_MIN^99MNDRY': ['kcal/kg/min', '10048', 'MNDRY_DIM_KILO_CAL_PER_KG_PER_MIN',
                                                            '99MNDRY', 'Miscellaneous']}
